spring.application.name=gotNow
spring.datasource.url=jdbc:mysql://localhost:3306/gotnowdb
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB


api.prefix=/api/v1
app.useSecureCookie=false


## 2 minutes
auth.token.accessExpirationInMils=120000
## 5 days
auth.token.refreshExpirationInMils=300000

## 5 minutes
#auth.token.accessExpirationInMils=300000
## 30 days
#auth.token.refreshExpirationInMils=2592000000

auth.token.jwtSecret=36763979244226452948404D635166546A576D5A7134743777217A25432A462D










# 5 minutes
##auth.token.refreshExpirationInMils=300000

## 39 days.
##auth.token.refreshExpirationInMils=2592000000

#spring.web.cors.allowed-origins=http://localhost:5173
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=*
